resolver: lts-9.6

flags: {}
packages:
- haskoin-core
- haskoin-node
- haskoin-wallet
extra-deps:
- daemons-0.2.1
- pbkdf-1.1.1.1
- secp256k1-0.4.8
- murmur3-1.0.3
- concurrent-extra-0.7.0.10
- aeson-1.2.2.0
### uncomment below for lts-7.18 compatibility
#- esqueleto-2.5.1
